### PR TITLE
fix "unparenthesized `a ? b : c ? d : e`"-Error in PHP8.0

### PR DESCRIPTION
**Pull request by Snck3rs**
Bei der Umstellung auf PHP8.0 in Contao 4.13.12 wird folgender Fehler ausgeworfen:

`request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: "Compile Error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`" at /var/www/web10/htdocs/dev/vendor/hofff/contao-rate-it/src/Rating/RatingService.php line 142 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Compile Error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` at /var/www/web10/htdocs/dev/vendor/hofff/contao-rate-it/src/Rating/RatingService.php:142)"} []`

### CODE REVIEW

**Comment by koertho** [comment]
Any news about this? Would be great to have this error fixed! :)

**Comment by dmolineus** [comment]
Thanks @Snck3rs for the pull request. Unfortunately the proposed solution is incorrect so I wasn't able to merge it. Release 0.4.2 fixes the issue.

**Comment by Snck3rs** [comment]
> Thanks @Snck3rs for the pull request. Unfortunately the proposed solution is incorrect so I wasn't able to merge it. Release 0.4.2 fixes the issue.

That's ok. It was just my attempt to solve it without any deeper insights. For me it worked fine, so i've thought it could be a solution. But i will take a look at the final fix.

**Comment by Snck3rs** [comment]
@dmolineus oh wait... i saw my mistake. i promise i will never use the online code editor again... sorry for that bs of mine

**Pull request closed without merging**
