### PR TITLE
Change css classes instead of removing/adding element

### PR DESCRIPTION
**Pull request by bytehead**
Possible fix for #15

### CODE REVIEW

**Comment by dmolineus** [comment]
The goal of the script is to support generic templates where icon can also be some images. Imagine icons are defined as:

```html
<svg class="hoff-rate-it-icon-rated"><!-- Inline svg --></svg>
<svg class="hoff-rate-it-icon-unrated"><!-- Inline svg --></svg>
<svg class="hoff-rate-it-icon-half"><!-- Inline svg --></svg>
```

I don't have a device to test it at the moment, maybe changing 

https://github.com/hofff/contao-rate-it/blob/38b9273325c62b91f38d294b5628f42de8c3d01f/src/Resources/public/js/script.js#L62-L67

to would already works?

```js
        star = this.widget.appendChild(star);
        if (this.enabled) {
            star.addEventListener('mouseover', this.createHoverHandler(i));
            star.addEventListener('click', this.createClickHandler(i));
        }
```

**Comment by bytehead** [comment]
I don't understand - it's just exchanging css classes - independent from the html element?

**Comment by dmolineus** [comment]
> I don't understand - it's just exchanging css classes - independent from the html element?

You expect that icons are defined by css classes, but the icon could be an image, e.g. in inline svg or an plain old img.

```html
<img src="rated.png" class="hoff-rate-it-icon-rated">
<img src="unrated.png" class="hoff-rate-it-icon-unrated">
<img src="half.png" class="hoff-rate-it-icon-half">
```

**Comment by bytehead** [comment]
the icon element doesn't matter at all. it would work with img/svg/whatever. it just selects based on css classes.

**Comment by dmolineus** [comment]
Wouldn't your proposed solution generate following output for a rating of `3.5`?

```html
<img src="unrated.png" class="hoff-rate-it-icon hoff-rate-it-icon-rated">
<img src="unrated.png" class="hoff-rate-it-icon hoff-rate-it-icon-rated">
<img src="unrated.png" class="hoff-rate-it-icon hoff-rate-it-icon-rated">
<img src="unrated.png" class="hoff-rate-it-icon hoff-rate-it-icon-half">
<img src="unrated.png" class="hoff-rate-it-icon hoff-rate-it-icon-unrated">
````

The point is that the `unrated.png` is shown all the time.

**Comment by dmolineus** [comment]
If my proposed fix doesn't work, we might need to register the listeners to the widget and not to the stars and add a data-attribute indicating the rating value when drawing the icons.

**Comment by bytehead** [comment]
> Wouldn't your proposed solution generate following output for a rating of `3.5`?
> 
> ```
> 
> 
> 
> 
> 
> ```
> 
> The point is that the `unrated.png` is shown all the time.

That's not the intended use of this I think?

**Comment by bytehead** [comment]
You can simply hide images you won't show by css and it's class e.g. `.hoff-rate-it-icon-unrated {display: none;}`

**Comment by bytehead** [comment]
> If my proposed fix doesn't work, we might need to register the listeners to the widget and not to the stars and add a data-attribute indicating the rating value when drawing the icons.

I don't know why this elements need to be removed from the DOM and then attached again with just different css classes. This fucks up the mentioned browsers, as the mouseover/click listeners get removed every time.

**Comment by bytehead** [comment]
Maybe it's more visible what the script does after I reverted the changes in the template (it works also without).

**Comment by dmolineus** [comment]
> I don't know why this elements need to be removed from the DOM and then attached again with just different css classes. This fucks up the mentioned browsers, as the mouseover/click listeners get removed every time.

I can only repeat myself: The goal of the script is to support generic templates where icon **can also be some images**. 

> That's not the intended use of this I think?

It is. I added examples to show what *should* be possible. You may not agree, but that's what the extension should do. The main issue however was not the redraw but the usage of the `mouseout` instead of the `mouseleave` event. I close this issue.

I'd appriciate if you test the fix (https://github.com/hofff/contao-rate-it/commit/947756f388c974dabc29e96794bd5741cd2ff098) and confirm that it works https://github.com/hofff/contao-rate-it/tree/fix/mouseout-event.

**Comment by bytehead** [comment]
> I can only repeat myself: The goal of the script is to support generic templates where icon can also be some images.

Then explain me please, why my suggested change won't work? 🙃

**Comment by dmolineus** [comment]
> Then explain me please, why my suggested change won't work? upside_down_face

As explained we might have images representing the stars. If you change the css classes of an `unrated.png` to `hofff-rate-it-icon-rated` it still visualizes an unrated icon.

**Comment by bytehead** [comment]
@dmolineus your fix works (tested on IE11). Thanks 👍

**Comment by dmolineus** [comment]
Thanks for your contribution and patience :-) Fix is released now.

**Comment by bytehead** [comment]
Thanks! 🙏

**Pull request closed without merging**
